## 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

## ctrl+m+m to quickly make code into text

2.4.1+cu121


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [3]:
#Scalar Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as a Python int
scalar.item()

7

In [6]:
#Vector
#You can determine number of dimensions using the number of pairs of square brackets. In this case, there is only one dimension
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [2,4,6],
                       [3,6,9]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 6, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [17]:
# A bit more practice because why not
tensor2 = torch.tensor([[[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12],
                        [13,14,15,16]]]])
#GUESS: tensor.ndim is equal to 4
#GUESS: tensor.shape is torch.Size(1,4,4); Answer was ([1,1,4,4])
tensor2.ndim
tensor2.shape

torch.Size([1, 1, 4, 4])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full on random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

`Torch Random Tensors`: https://pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6576, 0.3047, 0.9191, 0.4560],
        [0.8285, 0.7826, 0.7112, 0.4072],
        [0.2689, 0.0018, 0.2174, 0.3777]])

In [19]:
# Create a random tensor with a smilir shape to an image tensor
random_image_size_tensor = torch.rand(size=(4,224,224)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 224, 224]), 3)

###Zeros and Ones

In [20]:
#Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#Creating a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange() don't use torch.range() that is deprecated
oneToTen = torch.arange(start=1, end=11, step=1)
oneToTen

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
tenZeros = torch.zeros_like(input=oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Practice
one_to_five = torch.arange(1,6)
fiveZeros = torch.zeros_like(input=one_to_five)
fiveZeros


tensor([0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:** Tensor datatypes are one of the 3 big errors developers run into  with PyTorch and deep learning in general
1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [26]:
# Float 32 tensor
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # What type of data is the tensor?
                              device=None, # What device is the tensor on? (e.g. one tensor is on the CPU while the other is on the GPU)
                              requires_grad=False) #Whether or not to track gradients with this tensors operations
float32_tensor.dtype #Default datatype of tensors is float32. Unless you change it the datatype will stay a float32

torch.float32

In [27]:
float_16_tensor = float32_tensor.type(torch.float16) #torch.half is the same thing as float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.long)
int_32_tensor

tensor([3, 6, 8])

In [30]:
float32_tensor*int_32_tensor

tensor([ 9., 36., 72.])

### Getting information from tensors (Tensor Attributes)

1. Tensors not the right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Creating a tensor
some_tensor = torch.rand(3,4,dtype=torch.float64)
some_tensor

tensor([[0.6197, 0.2116, 0.7848, 0.7764],
        [0.5125, 0.0912, 0.6139, 0.0855],
        [0.1226, 0.6491, 0.1085, 0.3132]], dtype=torch.float64)

In [32]:
#Find some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6197, 0.2116, 0.7848, 0.7764],
        [0.5125, 0.0912, 0.6139, 0.0855],
        [0.1226, 0.6491, 0.1085, 0.3132]], dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [33]:
# Creating a tensor and adding 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiplying tensor by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Subtracting 10
tensor-10

tensor([-9, -8, -7])

In [36]:
# Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in nueral networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [37]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6766, 0.4263],
        [0.2593, 0.1666]])

In [38]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [41]:
%%time
value = 0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.45 ms, sys: 0 ns, total: 2.45 ms
Wall time: 5.23 ms


In [42]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 539 µs, sys: 0 ns, total: 539 µs
Wall time: 662 µs


tensor(14)

## One of the most common errors in deep learning is shape errors

In [43]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmol (it's just a way to write less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [50]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [51]:
tensor_B.T, tensor_B.T.shape #.T is the in_built function in PyTorch to transpose an array

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [52]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_b.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions have to match")
print("Output: \n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_b.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions have to match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, neab sum, etc (Tensor Aggregation)

In [59]:
# Creating a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
# Finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
# Finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
#Find the mean; Note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [60]:
## Finding the positional min and max in the tensor -> returns the index position of the target tensor
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, Stacking, Squeezing, Unsqueezing Tensors

* Reshaping - reshapes an input tensor to a defined ShapeType
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on stop of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Adds a `1` dimension to a target tensor
* Commute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [75]:
# Creating a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [76]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# Changing z changes x (Because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [84]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])